name: pull_request

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'
      - 'Makefile'
      - '.codebuild/**'

jobs:
  push:
    name: pull_request
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version number
        id: container-ver
        run: echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build and push
        id: container-build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: IMAGE_VERSION=${{ env.IMAGE_VERSION }}
          push: false
